### ISSUE TITLE
MMM-Hue module loading but nothing is shown

### ISSUE THREAD

**Issue by EtzBetz** [MitchSS/MMM-Hue#9]
Hello,

I just added the MMM-Hue module and also got the userid locally of my hue bridge and added it to the config of the module. Now when I restart the MM, I don't get anything visual from the module. The only thing I see in the browser console, is this:

MMM-Hue.js:73 Wohnzimmer Oben false
MMM-Hue.js:97 Object {name: "Wohnzimmer Oben", lights: Array[0], type: "Room", state: Object, recycle: false…}
MMM-Hue.js:73 Mein Zimmer false
MMM-Hue.js:97 Object {name: "Mein Zimmer", lights: Array[2], type: "Room", state: Object, recycle: false…}action: Objectclass: "Recreation"lights: Array[2]0: "3"1: "1"length: 2__proto__: Array[0]name: "Mein Zimmer"recycle: falsestate: Objecttype: "Room"__proto__: Object
MMM-Hue.js:73 Group for wakeup false
MMM-Hue.js:97 Object {name: "Group for wakeup", lights: Array[1], type: "LightGroup", state: Object, recycle: true…}
MMM-Hue.js:73 Schlafzimmer false
MMM-Hue.js:97 Object {name: "Schlafzimmer", lights: Array[0], type: "Room", state: Object, recycle: false…}
MMM-Hue.js:73 Group for wakeup false
MMM-Hue.js:97 Object {name: "Group for wakeup", lights: Array[1], type: "LightGroup", state: Object, recycle: true…}action: Objectlights: Array[1]0: "1"length: 1__proto__: Array[0]name: "Group for wakeup"recycle: truestate: Objecttype: "LightGroup"__proto__: Object
TypeError: Cannot read property 'getElementsByClassName' of null
    at updateModuleContent (http://localhost:8080/js/main.js:202:36)
    at Promise (http://localhost:8080/js/main.js:139:5)
    at updateDomWithContent (http://localhost:8080/js/main.js:137:10)
    at newContentPromise.then (http://localhost:8080/js/main.js:119:25)

The TypeError seems to come from MMM-Hue, since when I exclude the module from the main config.js, it disappears. Still I don't really know what's wrong with this, since I get objects returned, which are correct as far as I can see.

Can you guide me somewhere to solve this? Do you need any more information? I'd gladly provide them.

Greetings,
derRAV3N

**Comment by EtzBetz** [comment]
I failed by setting the position to "bottom-left" instead of "bottom_left"..
